# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMAVqo9rnAjeZbuRke6bpYjUf7Bx4AXa
"""

import seaborn as sns
import pandas as pd
import plotly.express as px

#wczytanie danych oraz zdefiniowanie nazw kolumn
#zaprezentowane dane to informacje na temat różnego rodzaju próbek z różnych odmian pszenicy
#siedem pierwszych zawiera informacje o cechach/wymiarach poszczególnych próbek, ostatnia kolumna zawiera numer klasy, do której dana próbka przynależy
df = pd.read_csv("seeds_dataset.txt", delim_whitespace=True)
df.columns=['pow', 'obw', 'zw','dl', 'szer', 'asym','bru','Pszenica']
print(df.head())

#wykres o równoległych osiach
fig = px.parallel_coordinates(df, dimensions=df.columns[0:7], color='Pszenica')
fig.show()

#usunięcie kolumny zw i asym
df=df.drop(columns=['zw','asym'])

fig = px.parallel_coordinates(df, dimensions=df.columns[0:5], color='Pszenica',
                              color_continuous_scale=px.colors.diverging.Fall,
                              color_continuous_midpoint=2)
fig.show() 

#wykres macierzowy - przypadek 1
fig = px.scatter_matrix(df,dimensions=df.columns[0:5],color='Pszenica',
                        color_continuous_scale=px.colors.diverging.Armyrose,
                        color_continuous_midpoint=2)
fig.show()

#wykres macierzowy - przypadek 2
sns.pairplot(df, hue='Pszenica', palette='husl', height=3)